services:
  resumind:
    build: .
    working_dir: /app
    container_name: resumind
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: pnpm run dev
    environment:
      - NODE_ENV=development
